cart/config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
end

cart/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

cart/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

cart/app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

cart/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

cart/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

cart/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

cart/app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

cart/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

cart/app/helpers/application_helper.rb
module ApplicationHelper
end

cart/app/helpers/carts_helper.rb
module CartsHelper
end

cart/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

cart/app/helpers/products_helper.rb
module ProductsHelper
end

cart/app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

cart/app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @order_items.size == 0 %>
  <p class="text-center">
    カートの中は空です。<%= link_to "こちら", root_path %>から商品をお選びください。
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

<% if @order_item.present? %>
  <p class="text-center">x個のアイテムが入っています
  <%= link_to "買い物を続ける", root_path %></p>
  <% end %>

cart/app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

cart/app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} 個の商品が入っています 
( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

cart/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingCartExample</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to "My Store", root_path %></h1>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>
    <hr>
    <%= yield %>
  </div>

</body>
</html>

cart/app/views/order_items/create.html.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  \(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

cart/app/views/order_items/destroy.html.erb
\(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
\(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

cart/app/views/order_items/update.html.erb
\(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
\(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

cart/app/views/products/index.html.erb
<div id='menu'>
  <li><%= "メニュー" %></li>
<ul>
   
   <li><%= link_to "冷蔵庫", "https://swdev-miz72.c9users.io/cart" %>
   <%= "5000円" %></li>
   <li><%= link_to "洗濯機","https://swdev-miz72.c9users.io/cart" %>
   <%= "10000円" %></li>
   <li><%= link_to "電子レンジ", "https://swdev-miz72.c9users.io/cart" %>
   <%= "3000円" %></li>
   <li><%= link_to "掃除機", "https://swdev-miz72.c9users.io/cart" %>
   <%= "8000円" %></li>
</ul>
</div>

cart/app/views/products/product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>