twitter/config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  get"application/L4"
  
  get'top/main'
  post'top/login'
  
  get'tweets/main'
  post'tweets/login'
  root'tweets#main'
  get'tweets/logout'
  get 'tweets/index'
  get 'tweets/newuser'
  post 'tweets/usercreate'
  
  post '/tweets/update',to:'tweets#update'
  get '/tweets/:id/show',to:'tweets#show'
end

twitter/app/models/tweet.rb
class Tweet < ActiveRecord::Base
    def hello
        logger.debug "かわべさん"
    end
end

twitter/app/models/user.rb
class User < ActiveRecord::Base
end

twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def L4
    session[:co] ||=0
    session[:co] = session[:co].to_i+1
    render text: session[:co]
  end
end

twitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def main
    if session[:login_uid] then
        redirect_to "/tweets/index"
    end
  end
  def login
    user = User.find_by(uid: params[:uid],pass: params[:pass])
    if user then 
        session[:login_uid] = params[:uid]
        redirect_to "/"
    else 
        render "error"
    end
  end
  def logout
    session.delete(:login_uid)
    redirect_to "/"
  end
  
  def newuser
  end
  
  def usercreate
    if params[:pass1] == params[:pass2] then
      user=User.new(uid: params[:uid],pass: paramas[:pass1])
      user.save
      redirect_to "/"
    else
      @error = "パスワードが違います"
      render "newuser"
    end
  end
  
  def index
    @error=nil
    @tweets = Tweet.all.reverse_order
    logger.debug "川邉"
  end
  
  def new
    @tweet=Tweet.new
  end
  
  def create
   tweet=Tweet.new(message: params[:tweet][:message],tdate: Time.current)
   tweet.save
   redirect_to root_path
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(message: params[:message],tdate: Time.current)
    redirect_to root_path
  end
end

twitter/app/helpers/application_helper.rb
module ApplicationHelper
end

twitter/app/helpers/tweets_helper.rb
module TweetsHelper
end

twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <%= yield %>
    
</body>
</html>

twitter/app/views/tweets/edit.html.erb
<%= form_tag('/tweets/update',method: :"post")do %>
  <%= hidden_field_tag :id, @tweet.id %>
  <%= text_area_tag :message, @tweet.message, size: "30×3", maxlength: "140" %>
  <%= submit_tag '更新' %>
<% end %>

twitter/app/views/tweets/error.html.erb
ログイン失敗</br>
<%= link_to "戻る","/" %>

twitter/app/views/tweets/index.html.erb
<body>
<div id="page">
<div id="pageSub">
      <h1 id="nameTitle">Miz</h1></br>
      近畿大学情報学科です</br>
      <p class="btn"><a href="a"><%=link_to'新規メッセージ',new_tweet_path %></a></p>
      <p class="btn"><a href="a"><%= link_to"DM","/tweets/new" %></a></p>
</div>



<div id="pageBody">
<% @tweets.each do |t| %>
  <font size="1"><%= ((Time.current - t.tdate)/60).to_i %>分前</br></font>
  <%= t.message %>
  <%= link_to "表示", "/tweets/#{t.id}/show" %>
  <%= link_to "編集", "/tweets/#{t.id}/edit" %>
  <%= link_to "削除","/tweets/#{t.id}",method: :delete %>
  <hr/>
<% end %>
</div>
</div>
</body>

twitter/app/views/tweets/main.html.erb
<%= form_tag '/tweets/login', method: :post do %>
  <%= label_tag :uid,'ユーザID' %>
  <%= text_field_tag :uid%>
  <%= label_tag :pass,'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag '登録' %>
<% end %>
<%= link_to "新規登録","/tweets/newuser" %>



<% @tweets.each do |e| %>
  <%= e.message %>
  <%= link_to 'いいね', likes_path(tweet_id: e.id),method: :post %>
  <%= link_to 'いいね削除', like_path(e),method: :delete %>
<% end %>

twitter/app/views/tweets/new.html.erb
<%= form_for @tweet, :message=>{action: :create} do |f| %>
  <%= f.label :message, 'メッセージ' %>
  <%= f.text_area :message %>
  <%= f.submit '投稿' %>
<% end %>

<% link_to "戻る","/" %>

twitter/app/views/tweets/newuser.html.erb
<%= @error %>

<%= from_tag '/twitterx/usercreate',method: :post do %>
  <%= label_tag :uid,'ユーザーID' %>
  <%= text_field_tag :uid %><br><br>
  <%= label_tag :pass1,'パスワード' %>
  <%= password_field_tag :pass1 %><br>
  <%= label_tag :pass2,'パスワード(確認)' %>
  <%= password_field_tag :pass2 %><br>
  <%= submit_tag '登録' %>
<% end %>
<%= link_to "戻る","/" %>

twitter/app/views/tweets/show.html.erb
<%= @tweet.message %></br>
<%= link_to "戻る" , "/" %>